# Core tmux options.

if-shell -F '#{==:#{@tmux_enable_mouse},1}' 'set-option -g mouse on' 'set-option -g mouse off'

# Change prefix to Ctrl-a.
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# Start window and pane numbering at 1.
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Keep more scrollback.
set -g history-limit 50000

# Better Vim responsiveness.
set -s escape-time 0

# True color.
set -g default-terminal "screen-256color"
set -ag terminal-overrides ",xterm-256color:RGB"
